export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const EXAMPLE_REQUEST_START = 'EXAMPLE_REQUEST_START';
export const EXAMPLE_REQUEST_DATA = 'EXAMPLE_REQUEST_DATA';
export const EVAL_ERROR = 'EVAL_ERROR';
export const EVAL_SUCCESS = 'EVAL_SUCCESS';
